### ISSUE TITLE
Custom resources are unrecognized

### ISSUE THREAD

**Issue by tallpants** [aws-cloudformation/cloudformation-cli#366]
Not sure if this is the right place to ask -- if it isn't please point me to where I _should_ be asking this.

I've got a custom resource, `validate` works, `generate` works, `submit` works, the deploy stage is `COMPLETED`, it shows up in the registry in the console -- and yet if I try to deploy a stack with the resource in the same region I get an unrecognized resource error from CloudFormation.

If a resource looks like it's been registered just fine but cloudformation can't seem to find it, what could be the cause / where should I be looking for mistakes?

Sorry again if this isn't the place to be asking!

**Comment by rjlohan** [comment]
Can you describe the error you see?

**Comment by tallpants** [comment]
It's literally just that unfortunately -- not much to go on:

```
$ aws cloudformation create-stack --region us-east-1 --template-body "file://template.yml" --stack-name "Test"

An error occurred (ValidationError) when calling the CreateStack operation: Template format error: Unrecognized resource types: [OurBranch::Custom::SSMParameterValue]
```

And here's the template:

```yaml
AWSTemplateFormatVersion: "2010-09-09"
Description: Test template for the OurBranch::Custom::SSMParameterValue resource type

Resources:
  SSMValueTest:
    Type: OurBranch::Custom::SSMParameterValue
    Properties:
      ParameterName: test_parameter
```

But it does seem to be registered in CloudFormation:

```
$ aws cloudformation list-type-versions --type "RESOURCE" --type-name "OurBranch::Custom::SSMParameterValue"

{
    "TypeVersionSummaries": [
        {
            "Type": "RESOURCE",
            "TypeName": "OurBranch::Custom::SSMParameterValue",
            "VersionId": "00000001",
            "Arn": "arn:aws:cloudformation:us-east-1:808503970309:type/resource/OurBranch-Custom-SSMParameterValue/00000001",
            "TimeCreated": "2019-12-11T18:55:41.798Z",
            "Description": "Resource that makes the latest version of an SSM parameter store value available to use in CloudFormation."
        }
    ]
}
```

**Comment by rjlohan** [comment]
Can you try publishing with a name that does not include `Custom::` in there? I'm wondering if our internal logic is still picking up that token when it's not the first token, and looking up a Custom Resource instead of going to the Registry. If that's the case, I'll file this as an internal bug to fix.

**Comment by jotompki** [comment]
If you describe the type using: `aws cloudformation describe-type --type-name "OurBranch::Custom::SSMParameterValue" --type RESOURCE`, is it marked as non provisionable? If so you may need to add a handler into your schema and implement it. To be provisionable by CloudFormation, custom resources need at minimum Create, Read, and Delete handlers.

**Comment by tallpants** [comment]
@jotompki you were right -- it's listed as non-provisionable. I wrote handlers for create read and delete, but they weren't part of the schema.

So I added them to the schema, and now I have `cfn validate` telling me the schema is valid, but `cfn submit` telling me that it isn't. Any idea what's up?

```
$ cfn validate
Resource specification for OurBranch::Custom::SSMParameterValue is valid

$ cfn submit -v --region us-east-1
Validating your resource specification...
Packaging Go project
Creating ourbranch-custom-ssmparametervalue-role-stack
ourbranch-custom-ssmparametervalue-role-stack already exists. Attempting to update
ourbranch-custom-ssmparametervalue-role-stack stack is up to date
Creating CloudFormationManagedUploadInfrastructure
CloudFormationManagedUploadInfrastructure already exists. Attempting to update
CloudFormationManagedUploadInfrastructure stack is up to date
Successfully submitted type. Waiting for registration with token 'f1ada20e-4ad6-4581-91ac-8f9ad823263d' to complete.
Failed to register the type with registration token 'f1ada20e-4ad6-4581-91ac-8f9ad823263d'.
Please see response for additional information: '{'ProgressStatus': 'FAILED', 'Description': 'Deployment is currently in VALIDATION_STAGE of status FAILED; Next is DEPLOY_STAGE with status CANCELLED\nDeployment failed with exception: com.amazonaws.providerruntime.utils.exceptions.ValidationException with error msg : [f1ada20e-4ad6-4581-91ac-8f9ad823263d] Error validating schema definition.', 'ResponseMetadata': {'RequestId': 'f10aab3d-94c0-48ab-bec1-596bfe5f3536', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': 'f10aab3d-94c0-48ab-bec1-596bfe5f3536', 'content-type': 'text/xml', 'content-length': '682', 'date': 'Wed, 11 Dec 2019 19:33:37 GMT'}, 'RetryAttempts': 0}}'
=== Caught downstream error ===
Waiter TypeRegistrationComplete failed: Waiter encountered a terminal failure state
---
If debugging indicates this is a possible error with this program,
please report the issue to the team and include the log file 'rpdk.log'.
Issue tracker: https://github.com/aws-cloudformation/aws-cloudformation-rpdk/issues
```

Here's the schema:

```
{
  "typeName": "OurBranch::Custom::SSMParameterValue",
  "description": "Resource that makes the latest version of an SSM parameter store value available to use in CloudFormation.",
  "sourceUrl": "https://github.com/gobranch/cfn-ssm-parameter-value-resource",
  "properties": {
    "ParameterName": {
      "description": "The name of the parameter in SSM parameter store.",
      "type": "string",
      "pattern": "^[a-zA-Z0-0_.-/]+$",
      "minLength": 1,
      "maxLength": 2048
    },
    "Value": {
      "description": "The value of the latest version of this parameter",
      "type": "string"
    }
  },
  "additionalProperties": false,
  "required": ["ParameterName"],
  "primaryIdentifier": ["/properties/ParameterName"],
  "readOnlyProperties": ["/properties/Value"],
  "handlers": {
    "create": {
      "permissions": ["ssm:GetParameter"]
    },
    "read": {
      "permissions": ["ssm:GetParameter"]
    },
    "update": {
      "permissions": ["ssm:GetParameter"]
    },
    "delete": {
      "permissions": []
    },
    "list": {
      "permissions": []
    }
  }
}
```

**Comment by tobywf** [comment]
Seems like a service-side issue, since that schema is perfectly valid. Looking into it, I'll leave this open for now, but it isn't a CloudFormation CLI issue as such. Good spot though!

**Comment by tallpants** [comment]
Any idea who I should bother for it @tobywf?

**Comment by rjlohan** [comment]
> Any idea who I should bother for it @tobywf?

Us. :)

You may be able to work around by adding an empty permissions block for each handler, e.g;

```
"list": {
  "permissions": [ "" ]
}
```

**Comment by tallpants** [comment]
That worked perfectly!

```yaml
AWSTemplateFormatVersion: "2010-09-09"
Description: Test template for the OurBranch::Custom::SSMParameterValue resource type

Resources:
  SSMValueTest:
    Type: OurBranch::Custom::SSMParameterValue
    Properties:
      ParameterName: es_host

Outputs:
  TestValue:
    Value: !GetAtt SSMValueTest.Value
    Export:
      Name: CustomResourcesTestValue
```

<img width="828" alt="Screenshot 2019-12-12 at 10 10 35 AM" src="https://@rjlohan r-images.githubusercontent.com/15325890/70683275-c22cb180-1cc7-11ea-98fb-48b3c46e6d3f.png">

Thanks so much @rjlohan @jotompki @tobywf !

**Comment by tallpants** [comment]
That worked perfectly!

```yaml
AWSTemplateFormatVersion: "2010-09-09"
Description: Test template for the OurBranch::Custom::SSMParameterValue resource type

Resources:
  SSMValueTest:
    Type: OurBranch::Custom::SSMParameterValue
    Properties:
      ParameterName: es_host

Outputs:
  TestValue:
    Value: !GetAtt SSMValueTest.Value
    Export:
      Name: CustomResourcesTestValue
```

Thanks so much @rjlohan @jotompki @tobywf !
