### ISSUE TITLE
Required IAM permission set for `cfn submit`

### ISSUE THREAD

**Issue by tomwwright** [aws-cloudformation/cloudformation-cli#558]
I'm working some deployment automation for a CloudFormation Resource Provider. I've used this project. I'm attempting at the moment to craft an IAM role for the deployment automation to use that runs the `cfn submit` command

I know it needs to be able to do all the CloudFormation Types stuff but also needs to be able to manage deploying the upload infra as well as the execution role stack.

Any resources or documentation available on this permission set?

**Comment by vmdude** [comment]
What we're using on our side:

```yaml
# BEGIN Necessary to create all infra modules for cfn modules feature
- action:
    - kms:*
    resource:
    - '*'
    effect: Allow
- action:
    - cloudformation:RegisterType
    - cloudformation:DescribeTypeRegistration
    - cloudformation:SetTypeDefaultVersion
    resource:
    - '*'
    effect: Allow
- action:
    - iam:CreateRole
    - iam:PutRolePolicy
    - iam:DeleteRolePolicy
    - iam:GetRole
    - iam:PassRole
    resource:
    - arn:aws:iam::{{ACCOUNT_ID}}:role/CloudFormationManagedUplo-LogAndMetricsDeliveryRol-*
    effect: Allow
- action:
    - s3:*
    resource:
    - arn:aws:s3:::cloudformationmanageduploadinfra*
    - arn:aws:s3:::cloudformationmanageduploadinfra*/*
    effect: Allow
# END Necessary to create all infra modules for cfn modules feature
```
