### ISSUE TITLE
Best way to handle external credentials

### ISSUE THREAD

**Issue by Giaco9** [aws-cloudformation/cloudformation-cli#630]
Hi everyone,
I'm implementing a custom resource provider that creates a Project into an external service. That service exposes a set of APIs that requires a token to authenticate the API call. My schema is:

```
{
    "typeName": "Company::ExternalService::Project",
    "description": "Create a project",
    "additionalProperties": false,
    "properties": {
        "ProjectName": {
            "description": "Name of the project",
            "type": "string",
            "pattern": "^[a-zA-Z0-9-_]{1,32}$"
        },
        "APIAccessToken": {
            "description": "API Access token to authenticate with the API",
            "type": "string"
        },
        "ProjectId": {
            "description": "ID of the new project",
            "type": "integer"
        },
        "CreationDate": {
            "description": "Creation date of the project",
            "type": "string"
        }
    },
    "required": [
        "ProjectName",
        "APIAccessToken"
    ],
    "readOnlyProperties": [
        "/properties/ProjectId",
        "/properties/CreationDate"
    ],
    "primaryIdentifier": [
        "/properties/ProjectId"
    ],
    "handlers": {
        "create": {
            "permissions":[]
        },
        "read": {
            "permissions": []
        },
        "delete": {
            "permissions": []
        },
        "list": {
            "permissions": []
        }
    }
}
```

To create a project I do the following:

```
Resources:
  ExternalServiceProject:
    Type: Company::ExternalService::Project
    Properties:
      ProjectName: NewProjectName
      APIAccessToken: <API Access Token From the secret store>

Ouputs:
  ProjectId:
     Value: !Ref ExternalServiceProject
  ProjectCreationDate:
      Value: !GetAtt ExternalServiceProject.CreationDate
```

The ExternalServiceProject physical resource id is "project$NewProjectName$<project-id-generated-by-the-external-service}"
Adding the ProjectCreationDate output when I create the stack, the project is created successfully but the subsequent read API call doesn't receive the APIAccessToken to describe the project created. Without the APIAccessToken, I can't call the API to describe the project and get the creation date. The delete request to roll back the progress creation receives the API Access Token and it is able to delete the project correctly.
Which is the best way to handle API credentials to external services? I don't want to put them as part of the physical resource id because is a secret, I don't want to put the Creation Date as part of the physical resource id because it doesn't scale as a solution. 

```
$ cfn --version
cfn 0.1.13
```

Cloudformation cli python plugin version: 2.1.4
Python 3.7

Thank you!
