### ISSUE TITLE
Bug: Malformed condition causes module type registration to hang

### ISSUE THREAD

**Issue by travbale** [aws-cloudformation/cloudformation-cli#660]
I tried making a simple module which had a typo in the condition section. When I ran validate it passed but when I went to submit the module the registration hung for a few hours before failing.

Template Fragment that triggers the Error  (in YAML for readability actual template was in JSON)
```yaml
AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  MyParameter:
    Type: String
    Default: "NOT_SET"

Conditions:
  MyCondition:
    Fn::Not:
    - Fn::Equal: # Should be Fn::Equals
      - Ref: MyParameter
      - "NOT_SET"
  
Resources:
  TestResource:
     Condition: MyCondition
     Type: AWS::CloudFormation::WaitConditionHandle
      Properties: {}
 ```
 
 During registration the process hangs. Inspecting the registration token via `describe-type-registration` yields the following:

```json
{
    "ProgressStatus": "IN_PROGRESS",
    "Description": "Deployment is currently in VALIDATION_STAGE of status IN_PROGRESS; Next is DEPLOY_STAGE with status PENDING"
}
```

It seems that this template has caused the `VALIDATION_STAGE` to hang in some manner. 

This locks out updating the module for several hours until it fails.
