### ISSUE TITLE
Stacks registering modules as in example can't be deleted

### ISSUE THREAD

**Issue by jfoy** [aws-cloudformation/cloudformation-cli#738]
If we register a CloudFormation module through a stack (for example, via a CI pipeline), the following template works the first time:

```yaml
---
Parameters:
  ModuleUrl:
    Type: String
Resources:
  Mod:
    Type: AWS::CloudFormation::ModuleVersion
    Properties:
      ModuleName: This::Is::My::MODULE
      ModulePackage: !Ref ModuleUrl
```

Using the same template to push the next version of the module will have no effect, since the first version published will remain the default version for users. In order for a new version we publish to be used, we have to make it the default:

```yaml
---
Parameters:
  ModuleUrl:
    Type: String
Resources:
  Mod:
    Type: AWS::CloudFormation::ModuleVersion
    Properties:
      ModuleName: This::Is::My::MODULE
      ModulePackage: !Ref ModuleUrl
  ModDefault:
    Type: AWS::CloudFormation:ModuleDefaultVersion
    Properties:
      Arn: !Ref Mod
```

`ModuleDefaultVersion` will throw an error if the module we pass to it is already the default version, which will be the case the first time we spin up any stack from this template. Following the [example](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudformation-moduledefaultversion.html#aws-resource-cloudformation-moduledefaultversion--examples--Specifying_the_default_module_version--yaml), we declare a dummy version whose only purpose is to make sure we can set ours as the default: 

```yaml
---
Parameters:
  ModuleUrl:
    Type: String
Resources:
  DummyMod:
    Type: AWS::CloudFormation::ModuleVersion
    Properties:
      ModuleName: This::Is::My::MODULE
      ModulePackage: !Ref ModuleUrl
  Mod:
    DependsOn: DummyMod
    Type: AWS::CloudFormation::ModuleVersion
    Properties:
      ModuleName: This::Is::My::MODULE
      ModulePackage: !Ref ModuleUrl
  ModDefault:
    Type: AWS::CloudFormation:ModuleDefaultVersion
    Properties:
      Arn: !Ref Mod
```

Now from CI we can use the same template to publish each release of a module. All well and good -- until we try to delete the stack, which gives the error:

```yaml
{
  "StackId": "arn:aws:cloudformation:us-west-2:xxxxxxxxxxxx:stack/module-test/x",
  "EventId": "Mod-DELETE_FAILED-2021-04-20T19:08:38.248Z",
  "StackName": "module-test",
  "LogicalResourceId": "Mod",
  "PhysicalResourceId": "arn:aws:cloudformation:us-west-2:xxxxxxxxxxxx:type/module/This-Is-My-MODULE/00000017",
   "ResourceType": "AWS::CloudFormation::ModuleVersion",
   "Timestamp": "2021-04-20T19:08:38.248000+00:00",
   "ResourceStatus": "DELETE_FAILED",
   "ResourceStatusReason": "Resource handler returned message: \"This type has more than one active version. Please deregister non-default active versions before attempting to deregister the type. (Service: CloudFormation, Status Code: 400, Request ID: x, Extended Request ID: null)\" (RequestToken: y, HandlerErrorCode: GeneralServiceException)",
   "ResourceProperties": "{ \"ModulePackage\": \"s3://my-bucket/extensions/this-is-my-module/md5.zip\", \"ModuleName\": \"This::Is::My::MODULE\" }"
}
```

How can we handle this using a standard CloudFormation stack workflow?
