### ISSUE TITLE
Mac EC2 instance provisioning via CF is failing

### ISSUE THREAD

**Issue by allanchua101** [aws-cloudformation/cloudformation-cli#765]
Hi guys,

I was trying to provision a MAC EC2 instance using the YAML below:

```yaml
  MacCIInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: mac1.metal
      ImageId: ami-04290cec436fa2a12 # macOS Big Sur 11.3.1
      Tags:
        - Key: Name
          Value: !Sub "${AppName}-cicd-server-mac"
      KeyName: !Ref SshKeyName
      IamInstanceProfile: !Ref CIInstanceRole
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeType: gp2
            VolumeSize: "100"
            Encrypted: "true"
      SubnetId:
        Fn::ImportValue: !Sub "${AppName}-pv-subnet-a"
      SecurityGroupIds:
        - !Ref CISecurityGroup
```

Upon release via CloudFormation CLI, I am getting the following error:

```sh
The requested configuration is currently not supported. Please check the documentation 
for supported configurations. (Service: AmazonEC2; Status Code: 400; Error Code: Unsupported; Request
```

Thanks in advance!
