### ISSUE TITLE
Pass in "Extra" Values

### ISSUE THREAD

**Issue by taylorbartley** [aws-cloudformation/cloudformation-cli#767]
Feature Request

I'd like to be able to pass in values for additional properties to the MODULE types. 

Example for a module named `ACME::FOO::LogGroup::MODULE`:
```
Parameters:
  FunctionName:
    Type: String

Resources:
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${FunctionName}
```

Example use case of a default property as defined by CloudFormation/API:
```
LogGroup:
    Type: ACME::FOO::LogGroup::MODULE
    Properties:
      FunctionName: !Ref SomeLambdaFunction
      RetentionInDays: 3 << "Default" Property.
```
