### ISSUE TITLE
Add block public access to Artifact/AccessLogs Buckets created by CloudFormation-CLI 

### ISSUE THREAD

**Issue by moharirn** [aws-cloudformation/cloudformation-cli#978]
**Issue:** `CloudFormationManagedUploadInfrastructure` Stack creates two Amazon Simple Storage Service (Amazon S3) buckets: `ArtifactBucket` and `AccessLogsBucket`. These buckets are not created with block public access permissions. 

**Workaround:** 

- Manually update the S3 bucket via Console after Stack creation
-  Modify the [template](https://github.com/aws-cloudformation/cloudformation-cli/blob/master/src/rpdk/core/data/managed-upload-infrastructure.yaml) to add the [PublicAccessBlockConfiguration](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-publicaccessblockconfiguration.html) property and update the stack. 

**Solution:**
Add the `PublicAccessBlockConfiguration` to the [template](https://github.com/aws-cloudformation/cloudformation-cli/blob/master/src/rpdk/core/data/managed-upload-infrastructure.yaml) as below:

```
      PublicAccessBlockConfiguration: 
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
```
