### ISSUE TITLE
CloudFormation silently doesn't associate second CloudFront function and produces no error.

### ISSUE THREAD

**Issue by garretwilson** [aws-cloudformation/cloudformation-cli#991]
I have a CloudFront distribution with a single function:

```yaml
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
…
        DefaultCacheBehavior:
…
          FunctionAssociations:
            - EventType: viewer-request
              FunctionARN: !GetAtt FooFunction.FunctionMetadata.FunctionARN
```

I deploy the stack using `aws cloudformation deploy …` and see that in the console the `FooFunction` has a status of `Deployed`.

I define another function in the CloudFormation template and call `aws cloudformation deploy …` again.

```yaml
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
…
        DefaultCacheBehavior:
…
          FunctionAssociations:
            - EventType: viewer-request
              FunctionARN: !GetAtt FooFunction.FunctionMetadata.FunctionARN
            - EventType: viewer-request
              FunctionARN: !GetAtt BarFunction.FunctionMetadata.FunctionARN
```

Note that both functions have `AutoPublish: true` set.

In the console both functions now appear under "Functions". The status of `FooFunction` still shows `Deployed`. However the status of `BarFunction` is `Published`. And if I click on `BarFunction`, under "Associated distributions" it says:

> This function is not associated with any distributions.

Yet it is clearly listed under `FunctionAssociations`.
