### ISSUE TITLE
AWS elastic load balancer stickiness didn't update with CloudFormation

### ISSUE THREAD

**Issue by garretwilson** [aws-cloudformation/cloudformation-cli#992]
I first raised this issue [on Stack Overflow](https://stackoverflow.com/q/75860647).

I had an AWS CloudFormation template for ECS with an elastic load balancer with sticky sessions turned on:

```yaml
  WebTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties: 
      …
      Port: 80
      Protocol: HTTP
      TargetGroupAttributes:
        - Key: stickiness.enabled
          Value: true
        - Key: stickiness.type
          Value: lb_cookie
```

I changed the back-end to be stateless, and updated the CloudFormation template by simply deleting the `TargetGroupAttributes` section.

```yaml
  WebTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties: 
      …
      Port: 80
      Protocol: HTTP
      TargetGroupAttributes:
        - Key: stickiness.enabled
          Value: true
        - Key: stickiness.type
          Value: lb_cookie
```

After all, the [`TargetGroupAttributes`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-targetgroup.html#cfn-elasticloadbalancingv2-targetgroup-targetgroupattributes) section is optional, and [`stickiness.enabled`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticloadbalancingv2-targetgroup-targetgroupattribute.html) defaults to `false`.

But after I redeployed the CloudFormation template, increasing minimum number of desired instances as a test, the number of instances went up but refreshing a page got the same instance each time. Sure enough, in the console if I edit the target group attributes, it shows "Stickiness" is still turned on!

I added back the `TargetGroupAttributes` section with `stickiness.enabled` explicitly turned off:

```yaml
  WebTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties: 
      …
      Port: 80
      Protocol: HTTP
      TargetGroupAttributes:
        - Key: stickiness.enabled
          Value: false
```

This was sufficient to turn off stickiness.

From a developer's viewpoint, I would suspect that CloudFormation, creating its graph of settings, didn't even include the `TargetGroupAttributes` section, so therefore it didn't compare the old `TargetGroupAttributes` subgraph for any changes. (But this is an obvious gotcha for graph comparison and splicing. It should be accounted for in the algorithm.)

Yet again, as with #989 and #991, some hidden settings in CloudFormation get stuck in some position, and I never know whether my deploy is really going to deploy everything or not.
